### ISSUE TITLE
Undesired error/info output included

### ISSUE THREAD

**Issue by saadq** [mattlyons0/ide-typescript-theia#5]
Hey, first off much thanks for creating this package! It is a huge improvement over `ide-typescript`.

The only issue I'm having is that it seems to be be including some other info messages that aren't related to my tsconfig. 

For example, when I have `"noUnusedParameters": false` in my `tsconfig.json`, it still gives some info:

<img width="1440" alt="screen shot 2018-11-07 at 10 27 05 pm" src="https://user-images.githubusercontent.com/5678694/48176110-c4f6ef00-e2dc-11e8-89be-c889d35301fd.png">

Changing it to `"noUnusedParameters": true` changes the output from an "info" to an "error":

<img width="1440" alt="screen shot 2018-11-07 at 10 36 39 pm" src="https://user-images.githubusercontent.com/5678694/48176348-9cbbc000-e2dd-11e8-868b-c82491ebc643.png">

I can't seem to do anything to get it to ignore unused parameters. Is this just a part of theia's language server or can this be configured from the package itself?

Thanks!

**Comment by mattlyons0** [comment]
Theia is pretty much a wrapper for `tsserver` (Microsoft's typescript server). It appears that setting `noUnusedParameters` to `false` turns it into `info` instead of `error` message type. I'll look into if there is a way to add an option ignore `info` type diagnostics tomorrow.

**Comment by mattlyons0** [comment]
The Diagnostics panel already allows you to hide different severity levels. ![screenshot](https://i.imgur.com/Rh7bhz2.png)
I'm not sure why its not in your screenshot but maybe its hidden because of your UI theme.

**Comment by saadq** [comment]
Yeah, my UI theme was hiding it. Hiding the Info with that button does hide it from the Diagnostics panel, but it still shows the underlines/icons in the editor itself. I'll try to look into it and see if there's a way to hide it from there as well.

**Comment by mattlyons0** [comment]
Hm yeah I notice that too. Also the statusbar tile for diagnostics doesn't filter with the filters. I think there are several improvements that could be made to how different levels of error messages are handled in `atom-ide-ui`. Basically I can filter different severity levels but that change would have to be made downstream of this (in `atom-languageclient`). If a external dependency needs changing it'd be best to change upstream (in `atom-ide-ui`) where it makes the most sense to expose the option. But it might be too hard to implement upstream. Needs some more investigation for sure.

**Comment by saadq** [comment]
Yeah, I see what you mean. In case anyone else runs into this, it's simple enough to manually hide the info stuff by putting this in your stylesheet:

```less
.diagnostics-gutter-ui-highlight-info, .icon.icon-info {
  display: none;
}
```

Anyways, appreciate you taking the time to look into this! Thanks again :)

**Comment by mattlyons0** [comment]
If you want a true quick and dirty way to hide different log levels you can modify the installed `atom-languageclient` itself.
Add a new line before this: https://github.com/atom/atom-languageclient/blob/840478c9d040b006e16f737049c63813aafad1e8/lib/adapters/linter-push-v2-adapter.ts#L55
To remove diagnostics of info level use this snippet `params.diagnostics = params.diagnostics.filter((diagnostic) => diagnostic.severity < 4? diagnostic : undefined)`
Severity 4 is info. This will get rid of the info warnings everywhere (in diagnostics, syntax underlines, tooltips...)
